### ISSUE TITLE
Cannot authorize a node

### ISSUE THREAD

**Issue by ihcomega56** [pyrsia/pyrsia#1583] opened 2023-02-02 23:43 UTC
### Steps taken/Steps to reproduce

When I try to authorize a node with v0.2.3 or newer, this error occurs on macOS and Windows.
v0.2.2 works well.

Followed the process in this doc https://pyrsia.io/docs/developers/build_from_source_docker/.
Also tried to clear transparency logs in my local machine.

(It does not seem to happen in integration tests)

```
./pyrsia authorize --peer 12D3KooWC4QSE6ymCQLNkbAzDo2cphE9adgiKzJAda9p5TEyoqmg
Authorize request failed with error: HTTP status error (500 Internal Server Error) for url (http://localhost:7889/authorized_node): "Failure while adding block to the blockchain: Anyhow Error"
```

### Log

```
 2023-02-02T23:32:39.687Z INFO  pyrsia_registry                     > 127.0.0.1:57392 "POST /authorized_node HTTP/1.1" 500 "-" "-" 26.139765ms
 2023-02-02T23:33:10.264Z INFO  pyrsia_registry                     > 127.0.0.1:57408 "GET /v2 HTTP/1.1" 200 "-" "-" 186.953µs
 2023-02-02T23:33:14.368Z DEBUG pyrsia::blockchain_service::event   > Handle BlockchainEvent: AddBlock { payload: [123, 34, 105, 100, 34, 58, 34, 52, 100, 97, 57, 98, 48, 50, 100, 45, 101, 100, 99, 56, 45, 52, 99, 101, 55, 45, 56, 55, 57, 53, 45, 57, 97, 98, 102, 102, 57, 99, 98, 52, 54, 101, 99, 34, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 116, 121, 112, 101, 34, 58, 110, 117, 108, 108, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 115, 112, 101, 99, 105, 102, 105, 99, 95, 105, 100, 34, 58, 34, 34, 44, 34, 110, 117, 109, 95, 97, 114, 116, 105, 102, 97, 99, 116, 115, 34, 58, 48, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 115, 112, 101, 99, 105, 102, 105, 99, 95, 97, 114, 116, 105, 102, 97, 99, 116, 95, 105, 100, 34, 58, 34, 34, 44, 34, 97, 114, 116, 105, 102, 97, 99, 116, 95, 104, 97, 115, 104, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 95, 104, 97, 115, 104, 34, 58, 34, 34, 44, 34, 97, 114, 116, 105, 102, 97, 99, 116, 95, 105, 100, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 95, 105, 100, 34, 58, 34, 34, 44, 34, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 49, 54, 55, 53, 51, 56, 48, 55, 57, 52, 44, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 34, 58, 34, 65, 100, 100, 78, 111, 100, 101, 34, 44, 34, 110, 111, 100, 101, 95, 105, 100, 34, 58, 34, 49, 50, 68, 51, 75, 111, 111, 87, 74, 120, 69, 107, 99, 52, 114, 72, 49, 49, 78, 101, 74, 98, 57, 68, 69, 78, 72, 77, 112, 90, 119, 56, 83, 80, 97, 70, 118, 117, 111, 98, 72, 113, 98, 106, 106, 85, 109, 55, 110, 114, 66, 80, 34, 44, 34, 110, 111, 100, 101, 95, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 34, 58, 34, 100, 55, 53, 52, 51, 99, 98, 97, 45, 56, 102, 56, 56, 45, 52, 101, 97, 97, 45, 98, 51, 98, 100, 45, 49, 101, 99, 50, 100, 101, 49, 56, 50, 50, 51, 97, 34, 125], sender: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) } }
 2023-02-02T23:33:14.391Z DEBUG pyrsia::blockchain_service::service > Blockchain sends broadcast block #2: Block { header: Header { parent_hash: HashDigest { multihash: Multihash { code: 27, size: 32, digest: [74, 82, 99, 151, 172, 155, 123, 69, 9, 110, 114, 211, 206, 169, 25, 230, 192, 127, 225, 199, 48, 231, 68, 119, 26, 113, 74, 59, 124, 126, 96, 225, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }, transactions_hash: HashDigest { multihash: Multihash { code: 27, size: 32, digest: [11, 112, 197, 99, 195, 238, 12, 72, 144, 223, 191, 158, 66, 225, 248, 182, 48, 124, 255, 58, 159, 212, 84, 7, 97, 82, 85, 229, 183, 172, 90, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }, committer: Address { peer_id: Multihash { code: 0, size: 36, digest: [8, 1, 18, 32, 95, 248, 212, 130, 57, 30, 146, 100, 228, 178, 85, 174, 2, 172, 26, 77, 54, 52, 207, 34, 113, 167, 149, 179, 37, 25, 213, 181, 168, 247, 25, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }, timestamp: 1675380794, ordinal: 2, nonce: 130848196799092367935305077737902855263, hash: HashDigest { multihash: Multihash { code: 27, size: 32, digest: [17, 115, 225, 2, 122, 31, 147, 177, 110, 153, 63, 0, 135, 105, 219, 219, 12, 215, 141, 208, 244, 136, 241, 123, 69, 253, 201, 228, 230, 103, 156, 177, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } } }, transactions: [Transaction { type_id: Create, submitter: Address { peer_id: Multihash { code: 0, size: 36, digest: [8, 1, 18, 32, 95, 248, 212, 130, 57, 30, 146, 100, 228, 178, 85, 174, 2, 172, 26, 77, 54, 52, 207, 34, 113, 167, 149, 179, 37, 25, 213, 181, 168, 247, 25, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }, timestamp: 1675380794, payload: [123, 34, 105, 100, 34, 58, 34, 52, 100, 97, 57, 98, 48, 50, 100, 45, 101, 100, 99, 56, 45, 52, 99, 101, 55, 45, 56, 55, 57, 53, 45, 57, 97, 98, 102, 102, 57, 99, 98, 52, 54, 101, 99, 34, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 116, 121, 112, 101, 34, 58, 110, 117, 108, 108, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 115, 112, 101, 99, 105, 102, 105, 99, 95, 105, 100, 34, 58, 34, 34, 44, 34, 110, 117, 109, 95, 97, 114, 116, 105, 102, 97, 99, 116, 115, 34, 58, 48, 44, 34, 112, 97, 99, 107, 97, 103, 101, 95, 115, 112, 101, 99, 105, 102, 105, 99, 95, 97, 114, 116, 105, 102, 97, 99, 116, 95, 105, 100, 34, 58, 34, 34, 44, 34, 97, 114, 116, 105, 102, 97, 99, 116, 95, 104, 97, 115, 104, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 95, 104, 97, 115, 104, 34, 58, 34, 34, 44, 34, 97, 114, 116, 105, 102, 97, 99, 116, 95, 105, 100, 34, 58, 34, 34, 44, 34, 115, 111, 117, 114, 99, 101, 95, 105, 100, 34, 58, 34, 34, 44, 34, 116, 105, 109, 101, 115, 116, 97, 109, 112, 34, 58, 49, 54, 55, 53, 51, 56, 48, 55, 57, 52, 44, 34, 111, 112, 101, 114, 97, 116, 105, 111, 110, 34, 58, 34, 65, 100, 100, 78, 111, 100, 101, 34, 44, 34, 110, 111, 100, 101, 95, 105, 100, 34, 58, 34, 49, 50, 68, 51, 75, 111, 111, 87, 74, 120, 69, 107, 99, 52, 114, 72, 49, 49, 78, 101, 74, 98, 57, 68, 69, 78, 72, 77, 112, 90, 119, 56, 83, 80, 97, 70, 118, 117, 111, 98, 72, 113, 98, 106, 106, 85, 109, 55, 110, 114, 66, 80, 34, 44, 34, 110, 111, 100, 101, 95, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 34, 58, 34, 100, 55, 53, 52, 51, 99, 98, 97, 45, 56, 102, 56, 56, 45, 52, 101, 97, 97, 45, 98, 51, 98, 100, 45, 49, 101, 99, 50, 100, 101, 49, 56, 50, 50, 51, 97, 34, 125], nonce: 301751321759758551923679109722725589467, hash: HashDigest { multihash: Multihash { code: 27, size: 32, digest: [137, 236, 153, 33, 89, 233, 209, 22, 243, 115, 152, 83, 250, 230, 207, 156, 221, 192, 62, 121, 222, 188, 185, 26, 199, 106, 123, 157, 80, 99, 113, 201, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }, signature: Signature { signature: ed25519::Signature(368FF91E54E236A857643F75D8774E21A234CE4538C02AE0AF53384EBAED466ED78BB930FE0863B6D1A006B074DD0362B31A98BA7E2661CC2149513523699C03) } }], block_signature: BlockSignature { signature: Signature { signature: ed25519::Signature(4CCBDE9196ADBECAD1D15643A19DC1C1FC995B83DEFB9576F8DAEEB6259A7D17B8880D16ABC2815E14B1F778A683EE2C43832ED93D97A8F97882D22FDC9E6606) }, public_key: [95, 248, 212, 130, 57, 30, 146, 100, 228, 178, 85, 174, 2, 172, 26, 77, 54, 52, 207, 34, 113, 167, 149, 179, 37, 25, 213, 181, 168, 247, 25, 89] } }
 2023-02-02T23:33:14.391Z DEBUG pyrsia::network::client             > p2p::Client::broadcast_block sent
 2023-02-02T23:33:14.392Z INFO  pyrsia::blockchain_service::service > Failed to broadcast block. Error = InsufficientPeers
 2023-02-02T23:33:14.392Z DEBUG pyrsia::docker::error_util          > Rejection: Rejection(RegistryError { code: Unknown("Failure while adding block to the blockchain: Anyhow Error") })
 2023-02-02T23:33:14.392Z DEBUG pyrsia::docker::error_util          > ErrorMessage: ErrorMessage { code: Unknown(""), message: "Failure while adding block to the blockchain: Anyhow Error" }
 2023-02-02T23:33:14.392Z INFO  pyrsia_registry                     > 127.0.0.1:57411 "POST /authorized_node HTTP/1.1" 500 "-" "-" 25.634699ms
```

### Experienced Instance of the bug

rustc: 1.66.1
OS: macOS
Git verson: Tag v0.2.3 and 5dfdef933a4efd303d9cbae618eab2fd99675208 (the latest in the main branch)

**Comment by fishseabowl** [comment] 2023-02-03 00:45
Duplicated with issue #1521

**Comment by dasmanas** [comment] 2023-02-03 03:37
closing the current issue as it is duplicate of https://github.com/pyrsia/pyrsia/issues/1521

**Closed by dasmanas** 2023-02-03 03:37 UTC
Labels: bug, triage
