### ISSUE TITLE
Allow a user to retrieve the transparency logs for an artifact using the CLI

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#688] opened 2022-05-12 17:47 UTC
Part 1: define what a uses wants to see and implement in a mocked way in the CLI

(Arrow 6b - https://pyrsia.io/docs/developers/pyrsia-high-level-overview/)

Since for searching the logs we need information from the docker manifest - it might make sense to duplicate/copy the manifest into the transparency log.

**Comment by betarelease** [comment] 2023-01-24 19:27
Depends on #1399

**Comment by dgarus** [comment] 2023-01-25 07:25
@erwin1 @betarelease

**Comment by betarelease** [comment] 2023-02-07 19:16
duplicate of #1399. Closing.

**Closed by betarelease** 2023-02-07 19:16 UTC
Labels: transparency log, cli
