### ISSUE TITLE
pyrsia build throws error 500

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#1307] opened 2022-11-18 18:11 UTC
### Steps taken/Steps to reproduce

```
steve@pyrsia-nightly-build:~$ pyrsia inspect-log docker --image debian:unstable-20221114-slim
[]
steve@pyrsia-nightly-build:~$ pyrsia build docker --image debian:unstable-20221114-slim
Build request failed with error: HTTP status server error (500 Internal Server Error) for url (http://localhost:7888/build/docker)
```

**Pyrsia CLI log**
Trying to add an image which doesn't exist in Pyrsia.  E.g. `bash:3.2.57`
```
manasd@manasd-mac 22-11-18 10:03:05 pyrsia % ./target/debug/pyrsia ping
Connection Successful !!
manasd@manasd-mac 22-11-18 10:05:43 pyrsia % curl http://0.0.0.0:7888/status
{"peers_count":1,"peer_id":"12D3KooWE89gSwyp1R8yi9CAhC6EB6AhnKfn7CmoTd2cf61ZY4x3","peer_addrs":["/ip4/100.64.0.1/tcp/53833/p2p/12D3KooWE89gSwyp1R8yi9CAhC6EB6AhnKfn7CmoTd2cf61ZY4x3","/ip4/127.0.0.1/tcp/53833/p2p/12D3KooWE89gSwyp1R8yi9CAhC6EB6AhnKfn7CmoTd2cf61ZY4x3","/ip4/192.168.86.208/tcp/53833/p2p/12D3KooWE89gSwyp1R8yi9CAhC6EB6AhnKfn7CmoTd2cf61ZY4x3"]}%                                                                            manasd@manasd-mac 22-11-18 10:05:50 pyrsia % ./target/debug/pyrsia config -s
Config file path: /Users/manasd/Library/Preferences/rs.pyrsia-cli/default-config.toml
host = '0.0.0.0'
port = '7888'
disk_allocated = '5.84 GB'
manasd@manasd-mac 22-11-18 10:17:26 pyrsia % ./target/debug/pyrsia inspect-log docker --image bash:3.2.57
[]
manasd@manasd-mac 22-11-18 10:06:00 pyrsia % ./target/debug/pyrsia build docker --image bash:3.2.57
Build request failed with error: HTTP status server error (500 Internal Server Error) for url (http://0.0.0.0:7888/build/docker)
manasd@manasd-mac 22-11-18 10:06:06 pyrsia %
```

**Pyrsia Node log**
```
2022-11-18T18:14:00.631Z DEBUG pyrsia::artifact_service::service    > Request build of Docker "bash:3.2.57"
2022-11-18T18:14:00.631Z DEBUG pyrsia::artifact_service::service    > Got local node with peer_id: PeerId("12D3KooWE89gSwyp1R8yi9CAhC6EB6AhnKfn7CmoTd2cf61ZY4x3")
2022-11-18T18:14:00.633Z DEBUG pyrsia::artifact_service::service    > Got authorized node with peer_id: PeerId("12D3KooWESWCgqtTAD7kJ6inmNZymaNWPZjzQJEsC4ApkvVY19k7")
2022-11-18T18:14:00.635Z DEBUG pyrsia::artifact_service::service    > Request build in authorized node from p2p network
2022-11-18T18:14:00.635Z DEBUG pyrsia::network::client              > p2p::Client::request_build PeerId("12D3KooWESWCgqtTAD7kJ6inmNZymaNWPZjzQJEsC4ApkvVY19k7"): Docker: "bash:3.2.57"
2022-11-18T18:14:00.635Z DEBUG pyrsia::network::client              > Build requested successfully
2022-11-18T18:14:00.635Z DEBUG pyrsia::network::event_loop          > Event loop :: send build request
2022-11-18T18:14:00.635Z DEBUG pyrsia::network::event_loop          > Event loop :: build request sent with id RequestId(4)
2022-11-18T18:14:00.635Z DEBUG pyrsia::network::event_loop          > RequestResponseMessage::OutboundFailure RequestId(4) with error DialFailure
2022-11-18T18:14:00.636Z DEBUG pyrsia::docker::error_util           > Rejection: Rejection(RegistryError { code: Unknown("Failed to initialize a build: Failed to dial the requested peer") })
2022-11-18T18:14:00.636Z DEBUG pyrsia::docker::error_util           > ErrorMessage: ErrorMessage { code: Unknown(""), message: "Failed to initialize a build: Failed to dial the requested peer" }
2022-11-18T18:14:00.636Z INFO  pyrsia_registry                      > 127.0.0.1:53985 "POST /build/docker HTTP/1.1" 500 "-" "-" 4.940568ms


```

### Expected Behavior

Build should be run

### Experienced Instance of the bug

pyrsia-node-0.2.0+2520

**Comment by fishseabowl** [comment] 2022-11-18 18:38
I tried images alpine:3.16 and bash:3.2.57 using the latest code with commit ce8eb66838c31bd00b1aa178c0d0003a3a73412c, but couldn't reproduce the issue.
```
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia inspect-log docker --image alpine:3.16  
[]
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16     
Build request successfully handled. Build with ID 6c7c1435-171a-4a2f-b667-79d4f2884277 has been started.
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia inspect-log docker --image bash:3.2.57
[]
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image bash:3.2.57
Build request successfully handled. Build with ID fe42ec34-e8d0-4a28-8680-eeee50722bcd has been started.
```

**Comment by erwin1** [comment] 2022-11-21 10:03
I was able to reproduce against the nightly cluster. The reason is very simple: the nightly cluster has a bunch of blocks/logs already and it takes some time to download them. So basically what is happening is that you're trying to request a build, but the log that marks who is an authorized build node wasn't received yet.

If you leave your node running for a couple of minutes, you'll see logs like 'Transparency log inserted into database' then the build trigger will succeed.

So first task resulting from this problem:
* Improve error messaging while the Pyrsia node is initializing (and doesn't know which node is authorized yet)

However, I'll also create another follow-up issue to
* investigate / speed-up the block initialization at start-up.

**Comment by betarelease** [comment] 2022-11-29 19:48
This was fixed by reinitializing the artifact directory.

**Closed by betarelease** 2022-11-29 19:48 UTC
Labels: bug, triage
