### ISSUE TITLE
Improve file IO code

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#23] opened 2021-11-10 14:00 UTC
Follow-up issue from PR #19 

Is it possible to move the handler file IO functions to a separate file? Those are most likely to change and it will remove some conflicts later.

**Comment by prince-chrismc** [comment] 2021-12-10 21:11
Duplicate of #24 https://github.com/pyrsia/pyrsia/pull/19#issuecomment-965609120

**Closed by prince-chrismc** 2021-12-10 21:11 UTC
