### ISSUE TITLE
In windows 10 pro, after startup, Pyrsia_node stops with an anyhow error

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1174] opened 2022-10-10 21:18 UTC
### Steps taken/Steps to reproduce

According to the tutorial documentation [quick-installation](https://github.com/pyrsia/pyrsia/blob/main/docs/tutorials/quick-installation.mdx)
 - Download the latest Windows installer from [release page](https://github.com/pyrsia/pyrsia/releases/).

 - Double-click to run the installer

 - Run

 ```sh
SET RUST_LOG=info
cd c:\Pyrsia\Pyrsia\service
pyrsia_node.exe
```
Then, Pyrsia_node stops and the output details are as follows:
```
C:\Pyrsia\Pyrsia\service>pyrsia_node
 2022-10-10T20:42:13.900Z INFO  pyrsia_node > Pyrsia Docker Node will start running on 127.0.0.1:7888
 2022-10-10T20:42:13.901Z INFO  pyrsia_node > Looking up bootstrap node
 2022-10-10T20:42:13.904Z INFO  pyrsia::network::event_loop > Local node is listening on "/ip4/127.0.0.1/tcp/55464/p2p/12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME"
 2022-10-10T20:42:13.928Z INFO  pyrsia::network::event_loop > Local node is listening on "/ip4/10.6.252.115/tcp/55464/p2p/12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME"
 2022-10-10T20:42:14.026Z INFO  pyrsia_node                 > Found bootstrap peer_addr "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx"
 2022-10-10T20:42:14.026Z INFO  pyrsia_node                 > Probing "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx"
Error: Anyhow Error

Caused by:
    Connection was closed before a response was received
```

### Expected Behavior

Pyrsia_node works fine or reports CLI option errors and help messages.

### Experienced Instance of the bug

OS: Windows 10 Pro
Pyrsia version: [0.2.0-rc1](https://github.com/pyrsia/pyrsia/tree/0.2.0-rc1)

**Comment by erwin1** [comment] 2022-10-10 21:40
@fishseabowl is the problem reproducible every time? Are you running Windows in a VM?
Can you run `pyrsia --version` and dump the output here.

**Comment by fishseabowl** [comment] 2022-10-10 22:25
@erwin1 I'm running on a Windows laptop, and it happens every time. 
```
C:\Users>pyrsia --version
pyrsia_cli 0.1.1 (a10aafac91aeec7afe009e9a5eab47c619dd8477)
```

**Comment by erwin1** [comment] 2022-10-11 08:46
@fishseabowl can you re-run with 
```
SET RUST_BACTRACE=1
SET RUST_LOG=trace
```

**Comment by jperedadnr** [comment] 2022-10-11 16:38
Just tested, and it works fine for me, using the release binaries.

Windows Server 2022 Datacenter 21H2 20348.1006 (AWS instance)

**Comment by jperedadnr** [comment] 2022-10-11 16:39
And now also tested an old Windows 7 Pro... works as well!

**Comment by fishseabowl** [comment] 2022-10-11 16:53
The issue remains as follows:
```
C:\Pyrsia\Pyrsia\service>SET RUST_LOG=debug

C:\Pyrsia\Pyrsia\service>pyrsia_node
 2022-10-10T22:36:07.966Z DEBUG pyrsia_node > Parse CLI arguments
 2022-10-10T22:36:07.966Z DEBUG pyrsia_node > Create p2p components
 2022-10-10T22:36:07.972Z DEBUG pyrsia_node > Start p2p event loop
 2022-10-10T22:36:07.979Z DEBUG pyrsia_node > Create blockchain service component
 2022-10-10T22:36:07.985Z DEBUG pyrsia_node > Create transparency log service
 2022-10-10T22:36:07.985Z DEBUG pyrsia_node > Create pyrsia services
 2022-10-10T22:36:07.986Z DEBUG pyrsia_node > Create build event client
 2022-10-10T22:36:07.986Z DEBUG pyrsia_node > Create artifact service
 2022-10-10T22:36:07.986Z DEBUG pyrsia_node > Create build service
 2022-10-10T22:36:07.987Z DEBUG pyrsia_node > Create verification service
 2022-10-10T22:36:07.987Z DEBUG pyrsia_node > Start build event loop
 2022-10-10T22:36:07.987Z DEBUG pyrsia_node > Setup HTTP server
 2022-10-10T22:36:07.988Z DEBUG pyrsia_node > Pyrsia Docker Node will bind to host = 127.0.0.1, port = 7888
 2022-10-10T22:36:07.988Z DEBUG pyrsia_node > Setup HTTP routing
 2022-10-10T22:36:07.988Z DEBUG pyrsia_node > Setup HTTP server
 2022-10-10T22:36:07.990Z INFO  pyrsia_node > Pyrsia Docker Node will start running on 127.0.0.1:7888
 2022-10-10T22:36:07.990Z DEBUG pyrsia_node > Start p2p components
 2022-10-10T22:36:07.991Z DEBUG pyrsia::network::client > p2p::Client::listen "/ip4/0.0.0.0/tcp/0"
 2022-10-10T22:36:07.991Z DEBUG libp2p_tcp              > listening on 0.0.0.0:0
 2022-10-10T22:36:07.991Z INFO  pyrsia_node             > Looking up bootstrap node
 2022-10-10T22:36:07.992Z DEBUG reqwest::connect        > starting new connection: http://boot.pyrsia.link/
 2022-10-10T22:36:07.992Z DEBUG hyper::client::connect::dns > resolving host="boot.pyrsia.link"
 2022-10-10T22:36:07.993Z DEBUG libp2p_tcp                  > New listen address: /ip4/10.6.252.115/tcp/55885
 2022-10-10T22:36:07.993Z DEBUG libp2p_swarm                > Listener ListenerId(17408123999119901277); New address: "/ip4/10.6.252.115/tcp/55885"
 2022-10-10T22:36:07.993Z INFO  pyrsia::network::event_loop > Local node is listening on "/ip4/10.6.252.115/tcp/55885/p2p/12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME"
 2022-10-10T22:36:07.994Z DEBUG libp2p_tcp                  > New listen address: /ip4/127.0.0.1/tcp/55885
 2022-10-10T22:36:07.994Z DEBUG libp2p_swarm                > Listener ListenerId(17408123999119901277); New address: "/ip4/127.0.0.1/tcp/55885"
 2022-10-10T22:36:07.995Z INFO  pyrsia::network::event_loop > Local node is listening on "/ip4/127.0.0.1/tcp/55885/p2p/12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME"
 2022-10-10T22:36:08.093Z DEBUG hyper::client::connect::http > connecting to 104.198.178.107:80
 2022-10-10T22:36:08.138Z DEBUG hyper::client::connect::http > connected to 104.198.178.107:80
 2022-10-10T22:36:08.138Z DEBUG hyper::proto::h1::io         > flushed 61 bytes
 2022-10-10T22:36:08.187Z DEBUG hyper::proto::h1::io         > parsed 3 headers
 2022-10-10T22:36:08.187Z DEBUG hyper::proto::h1::conn       > incoming body is content-length (187 bytes)
 2022-10-10T22:36:08.191Z DEBUG hyper::proto::h1::conn       > incoming body completed
 2022-10-10T22:36:08.191Z DEBUG reqwest::async_impl::client  > response '200 OK' for http://boot.pyrsia.link/status
 2022-10-10T22:36:08.191Z DEBUG hyper::client::pool          > pooling idle connection for ("http", boot.pyrsia.link)
 2022-10-10T22:36:08.196Z INFO  pyrsia_node                  > Found bootstrap peer_addr "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx"
 2022-10-10T22:36:08.197Z INFO  pyrsia_node                  > Probing "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx"
 2022-10-10T22:36:08.198Z DEBUG pyrsia::network::client      > p2p::Client::add_probe_address PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx") "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx"
 2022-10-10T22:36:12.972Z DEBUG libp2p_autonat::behaviour::as_client > Send dial-back request to peer 12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx.
 2022-10-10T22:36:12.973Z DEBUG pyrsia::network::event_loop          > Local Peer 12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME is dialing Peer 12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx...
 2022-10-10T22:36:12.978Z DEBUG libp2p_dns                           > Dialing /ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx
 2022-10-10T22:36:12.979Z DEBUG libp2p_tcp                           > dialing 104.198.178.107:44000
 2022-10-10T22:36:13.171Z DEBUG multistream_select::dialer_select    > Dialer: Proposed protocol: /noise
 2022-10-10T22:36:13.300Z DEBUG multistream_select::dialer_select    > Dialer: Received confirmation for protocol: /noise
 2022-10-10T22:36:13.347Z DEBUG libp2p_core::upgrade::apply          > Successfully applied negotiated protocol
 2022-10-10T22:36:13.348Z DEBUG multistream_select::dialer_select    > Dialer: Proposed protocol: /yamux/1.0.0
 2022-10-10T22:36:13.396Z DEBUG multistream_select::dialer_select    > Dialer: Received confirmation for protocol: /yamux/1.0.0
 2022-10-10T22:36:13.396Z DEBUG yamux::connection                    > new connection: a28af98b (Client)
 2022-10-10T22:36:13.399Z DEBUG libp2p_core::upgrade::apply          > Successfully applied negotiated protocol
 2022-10-10T22:36:13.403Z DEBUG libp2p_swarm                         > Connection established: PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx") Dialer { address: "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx", role_override: Dialer }; Total (peer): 1. Total non-banned (peer): 1
 2022-10-10T22:36:13.404Z DEBUG pyrsia_node                          > Blockchain start pulling from other nodes
 2022-10-10T22:36:13.404Z DEBUG yamux::connection                    > a28af98b: new outbound (Stream a28af98b/1) of (Connection a28af98b Client (streams 0))
 2022-10-10T22:36:13.404Z DEBUG pyrsia::blockchain_service::service  > Blockchain query ordinal from : PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx")
 2022-10-10T22:36:13.405Z DEBUG multistream_select::dialer_select    > Dialer: Proposed protocol: /libp2p/autonat/1.0.0
 2022-10-10T22:36:13.405Z DEBUG pyrsia::network::client              > p2p::Client::request_blockchain [4] form PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx")
 2022-10-10T22:36:13.406Z DEBUG yamux::connection                    > a28af98b: new outbound (Stream a28af98b/3) of (Connection a28af98b Client (streams 1))
 2022-10-10T22:36:13.406Z DEBUG multistream_select::dialer_select    > Dialer: Proposed protocol: /pyrsia-blockchain-update-exchange/1
 2022-10-10T22:36:13.532Z DEBUG multistream_select::dialer_select    > Dialer: Received confirmation for protocol: /libp2p/autonat/1.0.0
 2022-10-10T22:36:13.532Z DEBUG multistream_select::dialer_select    > Dialer: Received confirmation for protocol: /pyrsia-blockchain-update-exchange/1
 2022-10-10T22:36:13.535Z DEBUG pyrsia::network::blockchain_protocol > Blockchain::write_request sends: [4]
 2022-10-10T22:36:13.684Z DEBUG pyrsia::network::blockchain_protocol > Blockchain::read_response receives: [40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 2022-10-10T22:36:13.684Z DEBUG libp2p_core::upgrade::apply          > Successfully applied negotiated protocol
 2022-10-10T22:36:13.688Z DEBUG pyrsia::blockchain_service::service  > Blockchain query ordinal from : PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx")
 2022-10-10T22:36:13.692Z DEBUG pyrsia::network::client              > p2p::Client::request_blockchain [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] form PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx")
 2022-10-10T22:36:13.693Z DEBUG yamux::connection                    > a28af98b: new outbound (Stream a28af98b/5) of (Connection a28af98b Client (streams 2))
 2022-10-10T22:36:13.693Z DEBUG multistream_select::dialer_select    > Dialer: Proposed protocol: /pyrsia-blockchain-update-exchange/1
 2022-10-10T22:36:13.736Z DEBUG multistream_select::dialer_select    > Dialer: Received confirmation for protocol: /pyrsia-blockchain-update-exchange/1
 2022-10-10T22:36:13.736Z DEBUG pyrsia::network::blockchain_protocol > Blockchain::write_request sends: [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 2022-10-10T22:36:13.839Z DEBUG yamux::connection                    > a28af98b: connection reset
 2022-10-10T22:36:13.840Z DEBUG libp2p_swarm                         > Connection closed with error IO(Custom { kind: Other, error: A(YamuxError(Closed)) }): Connected { endpoint: Dialer { address: "/ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx", role_override: Dialer }, peer_id: PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx") }; Total (peer): 0.
 2022-10-10T22:36:13.842Z DEBUG libp2p_autonat::behaviour::as_client > Outbound Failure Connection was closed before a response was received when on dial-back request to peer 12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx.
 2022-10-10T22:36:13.846Z DEBUG libp2p_autonat::behaviour::as_client > Send dial-back request to peer 12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx.
 2022-10-10T22:36:13.847Z DEBUG pyrsia::network::event_loop          > Local Peer 12D3KooWDhPM5KmLwHsnAYJ2mSdkiPCB4RAcT2RNhitYLJ5YDwME is dialing Peer 12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx...
 2022-10-10T22:36:13.847Z DEBUG libp2p_dns                           > Dialing /ip4/104.198.178.107/tcp/44000/p2p/12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx
 2022-10-10T22:36:13.848Z DEBUG libp2p_tcp                           > dialing 104.198.178.107:44000
Error: Anyhow Error

Caused by:
    Connection was closed before a response was received
```

**Comment by fishseabowl** [comment] 2022-10-11 17:01
Interesting, after `SET RUST_BACKTRACE=1` and `SET RUST_LOG=trace`, there is no error output. Some details are as follows:
```
 2022-10-11T16:58:46.694Z TRACE yamux::connection                    > 0eed62a7: received: (Header Data 43 (len 19) (flags 0))
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: write: (WriteState::Init)
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Init)
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Header (offset 0))
 2022-10-11T16:58:46.694Z TRACE libp2p_noise::io                     > read: copied 56/56 bytes
 2022-10-11T16:58:46.694Z TRACE libp2p_noise::io                     > read: frame consumed
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Header (offset 12))
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (Header Data 43 (len 0) (flags 4))
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Body (header (Header Data 43 (len 0) (flags 4))) (offset 0) (buffer-len 0))
 2022-10-11T16:58:46.694Z TRACE yamux::connection                    > 0eed62a7: received: (Header Data 43 (len 0) (flags 4))
 2022-10-11T16:58:46.694Z TRACE yamux::connection::stream            > 0eed62a7/43: update state: (SendClosed RecvClosed Closed)
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: write: (WriteState::Init)
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Init)
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Header (offset 0))
 2022-10-11T16:58:46.694Z TRACE libp2p_noise::io::framed             > read state: Ready
 2022-10-11T16:58:46.694Z TRACE libp2p_noise::io::framed             > read state: ReadLen { buf: [0, 0], off: 0 }
 2022-10-11T16:58:46.694Z TRACE yamux::frame::io                     > 0eed62a7: write: (WriteState::Init)
 2022-10-11T16:58:46.695Z TRACE libp2p_noise::io::framed             > write state Ready
 2022-10-11T16:58:46.695Z TRACE yamux::connection::stream            > 0eed62a7/43: read 1 bytes
 2022-10-11T16:58:46.695Z TRACE yamux::connection::stream            > 0eed62a7/43: read 19 bytes
 2022-10-11T16:58:46.695Z DEBUG libp2p_core::upgrade::apply          > Successfully applied negotiated protocol
 2022-10-11T16:58:46.695Z TRACE yamux::frame::io                     > 0eed62a7: read: (ReadState::Header (offset 0))
 2022-10-11T16:58:46.695Z TRACE libp2p_noise::io::framed             > read state: ReadLen { buf: [0, 0], off: 0 }
 2022-10-11T16:58:46.695Z DEBUG libp2p_autonat::behaviour::as_client > Outbound dial-back request returned DialResponse { status_text: Some("dial failed"), result: Err(DialError) }.
 2022-10-11T16:58:46.695Z TRACE pyrsia::network::event_loop          > Handle AutonatEvent: OutboundProbe(Error { probe_id: ProbeId(22), peer: Some(PeerId("12D3KooWERQcvMrdmRc8a3oSuEDU2AmMZ974ADpisbbpFDrSZ8hx")), error: Response(DialError) })
```

**Comment by betarelease** [comment] 2022-10-12 20:11
I think this is an intermittent issue. 

There was an internet issue in the office and I noticed the same thing @fishseabowl did. 
Since the time internet issue stabilized I haven't seen this.

I restarted came back in an hour and then 2 hours and 4 hours and my pyrsia node still runs. I will keep this node running and do a another fresh run tomorrow. If both do not fail in this way we can close this for now.

**Comment by erwin1** [comment] 2022-10-12 20:25
It's a connection issue that seems to happen randomly. We shouldn't crash the process though but gracefully log an error and continue.

**Comment by betarelease** [comment] 2022-10-13 22:43
I tried this on two different networks at home and office. So far no failures. Also when it breaks it does show the same error as Connection closed. Probably we should fix this to be more graceful but for now if things fail because of network errors we can ask users to restart. Closing this in favour of fixing other pressing issues.

**Closed by betarelease** 2022-10-13 22:43 UTC
Labels: bug
