### ISSUE TITLE
Add brew install docs to quick start guide

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1204] opened 2022-10-14 08:24 UTC
Since we have a working brew install https://github.com/pyrsia/homebrew-pyrsia now, we should add those instructions to 
 `/docs/tutorials/quick-installation.mdx` as well

**Comment by dasmanas** [comment] 2022-10-14 16:54
I have similar story https://github.com/pyrsia/pyrsia/issues/1200 tracked under epic https://github.com/pyrsia/pyrsia/issues/1010.

**Comment by betarelease** [comment] 2022-10-21 14:53
Closing this as duplicate of #1200

**Closed by betarelease** 2022-10-21 14:53 UTC
Labels: triage
